permalink: /:year/:month/:day/:title.html
paginate: 10
markdown: redcarpet

# 作者信息
author: 
  name: angela
  email: zuchuang1@gmail.com
  link: http://angelas.cc/other
  weibo: http://weibo.com
  github: http://github.com/angela0

# 站点信息
title: angela's other 
description: angela's other
url: http://angelas.cc/other
rss_url: ./pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/icon/Saphira.jpg
favicon: /public/upload/icon/favicon.ico

# google analytics 设置
ga:
  id: 
  url: angelas.cc

# disqus 设置
disqus:
  shortname: angela-zh

# 主题设置，自动激活某个标签
active: 文章

# 首页除了最新文章外显示分类
cates: 
  - BeautifulA
  - OpenStack

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
  archive: 归档
